# Generated by Django 5.0.6 on 2024-09-28 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_contact_email_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
    ]
